### ISSUE TITLE
typo in blog-post-preview.module.css

### ISSUE THREAD

**Issue by cluk3** [sanity-io/sanity-template-gatsby-blog#118]
https://github.com/sanity-io/sanity-template-gatsby-blog/blob/f82248644ed2fcf8215a9023a14db26fe0543d20/template/web/src/components/blog-post-preview.module.css#L5

It probably should be `display: block` instead of `display: blog`.
At first I thought it was some postcss plugin doing some magic trick ( I also spent some time googling it!) but then I saw it get's through the compilation unchanged...

**Comment by kmelve** [comment]
🤦 

Great catch – sorry for the confusion! Fix coming up!

**Comment by kmelve** [comment]
Fixed in https://github.com/sanity-io/sanity-template-gatsby-blog/commit/fd3b7816583d77772a517aef04ea53971dec9ff9

**Comment by cluk3** [comment]
that was fast!
thanks for the great job your doing :)
