### ISSUE TITLE
Update Gatsby version to V3

### ISSUE THREAD

**Issue by mattwelson** [sanity-io/sanity-template-gatsby-blog#150]
Gatsby has released a new version, including a new image plugin.

**Comment by bjoerge** [comment]
👋   @mattwelson we are working on gatsby-v3 support. If you'd like you can create a new project from the `gatsby-v3` branch here: https://www.sanity.io/create?template=sanity-io%2Fsanity-template-gatsby-blog&ref=gatsby-v3

**Comment by bjoerge** [comment]
Projects created from this template are now using Gatsby v3 and [gatsby-source-sanity](https://github.com/sanity-io/gatsby-source-sanity/) v7 which was just released.

**Comment by mattwelson** [comment]
Thanks @bjoerge
