### ISSUE TITLE
Excerpt is never used in SEO description. How to do PortableText to unformatted string?

### ISSUE THREAD

**Issue by Jakst** [sanity-io/sanity-template-gatsby-blog#5]
The following line is present as description of the `Excerpt` field in the blog editor of this studio example.

> This ends up on summary pages, on Google, when people share your post in social media.

However, it is never used as such. I was looking for a way to actually use the excerpt field as meta description for google, but I've found no way to render PortableText to an unformatted string. At least not without manually implementing serializers that return clean strings, but then I have to know every possible object type that could be used in the portable text.

Could you provide an example of this?

**Comment by kmelve** [comment]
Good catch! I've added the excerpt (and image) to the open graph fields in this template now. You can see how this is implemented by looking at this commit: https://github.com/sanity-io/sanity-template-gatsby-blog/commit/c6d4e03c4ea81c134bc6cef1aa8c0abc8e8c74d7 

The code to convert Portable Text to an unformatted string is found [here](https://github.com/sanity-io/sanity-recipes/tree/master/snippets).
